development:
  adapter: postgresql
  encoding: unicode
  database: spoonly
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: spoonly_test
  pool: 5

production:
  adapter: postgresql
  url: <%= ENV['POSTGRESQL_URL'] %> #This is the environment variable created by our Dokku command earlier
  encoding: unicode
  pool: 5
